### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by Rendaw** [jfager/jdiscript#6]
I got this error:
```
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make public synchronized void com.sun.tools.jdi.EventRequestManagerImpl$ClassPrepareRequestImpl.addSourceNameFilter(java.lang.String) accessible: module jdk.jdi does not "opens com.sun.tools.jdi" to module jdiscript.v0v
```

(jdiscript.v0v is a release on my fork of StareInTheAir's fork to get a java9 module compatible name)

This is in the setAccessible(true) call in the event proxy constructor.

**Comment by jfager** [comment]
Should just need to add 

    module jdiscript.v0v {
         opens com.sun.tools.jdi;
   }

right?  I haven't worked with Java 9 or modules at all yet.  Will try to take a look this weekend.

**Comment by Rendaw** [comment]
Oh, is that it :P ?  That makes sense, I haven't gotten wrapped around java 9 modules yet either.

**Comment by jfager** [comment]
So I started looking at this.  Just running jdiscript under jdk 9 shouldn't be an issue b/c the '--illegal-access=permit' jvm flag is the default, it just gives a warning, and you can get rid of the warning by passing '--add-opens jdk.jdi/com.sun.tools.jdi=ALL-UNNAMED'.

So I'm guessing you're specifically hitting the exception when you're actually trying to turn jdiscript into a module (which is what you said, I just didn't fully grok what you meant and assumed this was a problem with jdk9 in general).

Can you convince me that modularizing jdiscript is a good thing to do?  I'm through a paragraph of the quick-start guide and I'm already annoyed that it wants me to use a new directory layout ("by convention" only, but still) and that it uses a '.java' file for the module declaration (which is a headache for supporting compiling for both Java 8 & 9 out of the same codebase).  I don't personally have a need/use case for modules yet, can you explain what the win would be?

**Comment by Rendaw** [comment]
Sorry, I'm not sure what I was doing wrong.  I was getting an exception and my jdiscript program was quitting, but now it just warns and continues.

It says `WARNING: All illegal access operations will be denied in a future release`, but I guess in that case I just need to run the jdiscript program (not the program being debugged) with `--add-opens jdk.jdi/com.sun.tools.jdi=ALL-UNNAMED` as you said, which works fine for me.

I thought that jdiscript would simply not run with java 9 targets as it is now, but that doesn't seem to be the case.  Thanks for looking at this, and sorry for the confusion!
