### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Rendaw** [jfager/jdiscript#7]
Would you please include a license file?  If you have no preference, I like the BSD 2 clause license :)

I'm interested in making some of the other changes in a fork and publishing to a maven repo but I'm not sure it's allowed without one.

**Comment by jfager** [comment]
Will prob go with Apache 2.  Will get added this weekend.  

I've got the jdiscript.org domain name and am happy to publish to maven, have just never done it b/c have never gotten the interest.  If you have other changes in mind happy to take PRs or work on them.

**Comment by Rendaw** [comment]
Awesome!  This is a cool library.  I've published exactly one artifact to Sonatype's repo and it wasn't too difficult, just had a bunch of steps - glad to help if I can.  I think it's best to have the author publish it so people recognize the signature (maybe?).

If I have some time in the next couple weeks I wouldn't mind maybe looking at Java 9, although it seems like you know more about that than me.

**Comment by jfager** [comment]
Done, Apache 2.
